### ISSUE TITLE
Timer for Arena games is always a few seconds to 15 seconds slow.

### ISSUE THREAD

**Issue by denumerable** [DeadlyBossMods/DBM-PvP#113]
Title. I can reproduce or make a video if you'd like.

**Comment by denumerable** [comment]
This is in TBCC.

**Comment by QartemisT** [comment]
This issue is mainly due to the fact that when blizzard fires a TIMER_START event, it can be COMPLETELY off (it even happens with their own official timers too...).
It should attempt to do a recovery on the 15 second / 30 second / 60 second message however.

**Comment by denumerable** [comment]
Hi QartemisT. Yeah, that makes sense. I've done several hundred games over the last season and, yesterday, since updating, we did around 60 games. Not a single timer was correct. Usually it's about 5 seconds off (gates open with 5s or so remaining).

Most of the time we zoned in right as the queue popped.

**Comment by QartemisT** [comment]
Should be more accurate as of changes I did here:
https://github.com/DeadlyBossMods/DBM-PvP/commit/ace27d1819321da2aef790c9855dc47427152ff6
