### ISSUE TITLE
AV timers seems broken in wotlk

### ISSUE THREAD

**Issue by Nillx** [DeadlyBossMods/DBM-PvP#116]
Did a few AVs today and it doesnt really show any timers or if it does they are wrong. Wotlk prepatch.

**Comment by sippycupmcjr** [comment]
To be clear, the timers start when a team recaptures a tower/graveyard (e.g., Horde captures a bunker [no timer] and then Alliance recaptures a bunker [timer starts])

**Comment by dreamscape89** [comment]
The timers are broken in the pre-patch. They randomly appear and disappear, sometimes they don't appear at all.

**Comment by QartemisT** [comment]
This is being investigated shortly. :)

**Comment by jarveson** [comment]
if its any help, removing `isTbc` from here fixes it them as far as i can tell<https://github.com/DeadlyBossMods/DBM-PvP/blob/690609847024101dc9e551a0a97d9ec051791876/DBM-PvP/PvPGeneral.lua#L377-L385> not sure of any other changes, but looks like they swapped to retail values for this, and looks like they kept 
`WOW_PROJECT_ID = (WOW_PROJECT_BURNING_CRUSADE_CLASSIC)` for wrath :P

**Comment by QartemisT** [comment]
Could you try the alpha version? That was all changed to support wrath 🗡️

**Comment by legoman60** [comment]
Alpha version has the same issue.

**Comment by jarveson** [comment]
if its ur recent commits, no
https://github.com/DeadlyBossMods/DBM-PvP/blob/81e443d7f4dc1a9f7a49aa528d25de24aae24809/DBM-PvP/PvPGeneral.lua#L381

wrath is using 'retail' values here, so check should be `not isRetail and not isWrath and 3 or 4` or something similar

havent checked anything else, just been grinding av :P

**Comment by jarveson** [comment]
also https://github.com/DeadlyBossMods/DBM-PvP/blob/81e443d7f4dc1a9f7a49aa528d25de24aae24809/DBM-PvP/PvPGeneral.lua#L514 needs to be changed from 2000 to 1600 in the three spots there for arathi

**Comment by QartemisT** [comment]
These have been updated in latest alpha :)

**Comment by legoman60** [comment]
The most recent file on curseforge has fixed this issue (r135-9-g2923988).

**Comment by MysticalOS** [comment]
All BGs should be fixed. Tagged a new release and closing this issue for now since I'm pretty sure AB and AV issues all resolved.
