### ISSUE TITLE
Alterac Valley "boss" timers

### ISSUE THREAD

**Issue by jeichenhofer** [DeadlyBossMods/DBM-PvP#12]
Once each boss (Lokholar and Ivus) has been summoned, they announce themselves and patrol the field of strife for 10 minutes. I think we could implement a simple chat filter that waits for either announcement and creates a 10 minute timer to track when it starts moving.

I'm not familiar enough with the structure of the mod to do this myself yet, but I'm thinking it will mirror the event mechanism for the Ragnaros pull.

Relevant Chat Filter Code:
https://github.com/DeadlyBossMods/DBM-Classic/blob/940421df63534665d98affea42a6736ab5714a9a/DBM-MC/Ragnaros.lua#L13
https://github.com/DeadlyBossMods/DBM-Classic/blob/940421df63534665d98affea42a6736ab5714a9a/DBM-MC/Ragnaros.lua#L106

Docs for the "CHAT_MSG_MONSTER_YELL" event: https://wow.gamepedia.com/CHAT_MSG_MONSTER_YELL

I believe these are the quotes that each boss yells when summoned, but it would need to be confirmed and of course translated for localization:

> WHO DARES SUMMON LOKHOLAR? The blood of a thousand Stormpike soldiers shall I spill...none may stand against the Ice Lord!

> Wicked, wicked, mortals! The forest weeps. The elements recoil at the destruction. Ivus must purge you from this world!

**Comment by Developaws** [comment]
Indeed, Alterac Valley is due to recieve its boss timers as per #1, so I'll keep all conversation regarding that centralised till I work on it :)

**Comment by QartemisT** [comment]
@jeichenhofer Just a ping notice to say that this was implemented a few days ago :D
