### ISSUE TITLE
Cata Classic - Arathi exception

### ISSUE THREAD

**Issue by ZeChrales** [DeadlyBossMods/DBM-PvP#156]
Hey, in prepatch, for Arathi, every tick there is an exception related to alliance score (as horde player) :

Stack: Interface/AddOns/DBM-PvP/PvPGeneral.lua:487: attempt to perform arithmetic on local 'allianceScore' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/DBM-PvP/PvPGeneral.lua"]:487: in function `UpdateWinTimer'
[string "@Interface/AddOns/DBM-PvP/PvPGeneral.lua"]:673: in function `handler'
[string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:995: in function <Interface/AddOns/DBM-Core/DBM-Core.lua:982>

**Comment by MysticalOS** [comment]
@QartemisT can you check data and see if cata has yet another unique widget ID or something that contains the missing data?
