### ISSUE TITLE
Eye of the Storm

### ISSUE THREAD

**Issue by quixoticlizzie** [DeadlyBossMods/DBM-PvP#16]
**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**
During Eye of the Storm, bugsack picks up errors and repeatedly tells me so.

**Do you have an error log of what happened?**
Attached

**To Reproduce**
Go to Eye of the Storm

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No (if I get Eye of the Storm again will attempt)
**Which version of DeadlyBossMods are you using?**
8.3.15
**Was it working in a previous version? If yes, which was the last good one?**
Not sure - Don't regularly pvp
**Additional context**
I got Eye of the Storm via random bg queue and this happened. 
[bug.txt](https://github.com/DeadlyBossMods/DBM-PvP/files/4306448/bug.txt)
[bug2.txt](https://github.com/DeadlyBossMods/DBM-PvP/files/4306449/bug2.txt)

**Comment by Developaws** [comment]
Your version of DBM-PvP is outdated, please update it =]
