### ISSUE TITLE
another LUA error now in Seething Shore

### ISSUE THREAD

**Issue by milotic** [DeadlyBossMods/DBM-PvP#161]
**Describe the bug**
**Do you have an error log of what happened?**
Date: 2024-07-22 16:43:31
ID: 35
Error occured in: Global
Count: 1
Message: ...rface/AddOns/DBM-PvP/Battlegrounds/SeethingShore.lua line 67:
   bad argument #1 to 'format' (number expected, got string)
Debug:
   [string "=[C]"]: format()
   [string "@Interface/AddOns/DBM-PvP/Battlegrounds/SeethingShore.lua"]:67: handler()
   [string "@Interface/AddOns/DBM-Core/DBM-Core.lua"]:1046:
      Interface/AddOns/DBM-Core/DBM-Core.lua:1033
Locals:
(*temporary) = "Hello? Vignette position is empty. X: %f, Y: %f"
(*temporary) = "nil"
(*temporary) = "nil"
(*temporary) = "number expected, got string"

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes 

**Which version of DeadlyBossMods are you using?**

r178

**Comment by QartemisT** [comment]
Fixed =] <https://github.com/DeadlyBossMods/DBM-PvP/commit/7d4e39cb2c37c841aeeacd2e39c791c7b175c702>
