### ISSUE TITLE
Boss Meters in AV

### ISSUE THREAD

**Issue by Havenloft** [DeadlyBossMods/DBM-PvP#18]
I would like to see something similar to Capping. Where when a Boss Mob such as Vanndar Stormpike or Drek or Galv or Balinda or Lok'thar is engaged we can see the progress from anywhere on the map. With this feature in DBM I could stop using Capping entirely.

It would probably be even more accurate or better if it was compatible with the Capping addon so that users of either addon could share the information with each other.

**Comment by QartemisT** [comment]
Yep, this is already in the plans as part of #1, so I will keep any updates localised to there.
