### ISSUE TITLE
Lua error in Temple of Kotmogu

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-PvP#2]
**Describe the bug**
Throws error multiple times while playing Temple of Kotmogu. I don't really know after what event exactly, probably after first orb pick up and it continued until the end of match.

**Do you have an error log of what happened?**
Message: Interface\AddOns\DBM-PvP\PvPGeneral.lua:412: attempt to index local 'info' (a nil value)
Time: Thu Oct  3 22:44:04 2019
Count: 2
Stack: Interface\AddOns\DBM-PvP\PvPGeneral.lua:412: attempt to index local 'info' (a nil value)
[C]: ?
Interface\AddOns\DBM-PvP\PvPGeneral.lua:412: in function `handler'
Interface\AddOns\DBM-Core\DBM-Core.lua:800: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:787>

Locals: 

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Play match :)
2. See error

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
Latest alpha

**Was it working in a previous version? If yes, which was the last good one?**
I'm not sure, I don't do PvP that often.

**Comment by Developaws** [comment]
Resolved as of https://github.com/DeadlyBossMods/DBM-PvP/commit/9f42fdefe890241e056ee7f46ebbc8b3592eff11
