### ISSUE TITLE
Seething Shore bugs

### ISSUE THREAD

**Issue by MysticalOS** [DeadlyBossMods/DBM-PvP#35]
Maybe this BG Spams START_TIMER every 5 seconds who knows, but i watched it happening on Asmons stream last night. It made it so the timer never actually filled, because it kept restarting with new remaining time, over and over and over again right up until BG started.

If a timer already exists, and remaining time is not wrong, it shouldn't be started again.

if remaining time is wrong, but within a reasonable variation, :Update method should be used to update existing timer so fill progress is retained.

**Comment by MysticalOS** [comment]
Addiional bug, the cap or whatever timer on this BG just shows up as "Unknown"

**Comment by QartemisT** [comment]
https://cdn.discordapp.com/attachments/419696269456572416/766771845918883900/unknown.png
