### ISSUE TITLE
Lua error in Silvershard Mines

### ISSUE THREAD

**Issue by drgrejuva** [DeadlyBossMods/DBM-PvP#39]
Message: ...ce\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:172: attempt to perform arithmetic on local 'x' (a table value)
Time: Fri Oct 16 01:09:50 2020
Count: 14
Stack: ...ce\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:172: attempt to perform arithmetic on local 'x' (a table value)
[string "@Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua"]:172: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:856: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:843>

Locals: self = <table> {
 timers = <table> {
 }
 specwarns = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:14
 SyncThreshold = 8
 CHAT_MSG_BG_SYSTEM_HORDE = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:45
 modId = "DBM-PvP"
 shortTermEventsRegistered = 1
 shortTermRegisterEvents = <table> {
 }
 stats = <table> {
 }
 PVP_VEHICLE_INFO_UPDATED = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:168
 zones = <table> {
 }
 revision = 20201014230650
 Options = <table> {
 }
 DefaultOptions = <table> {
 }
 id = "z727"
 CHAT_MSG_BG_SYSTEM_NEUTRAL = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:45
 CHAT_MSG_BG_SYSTEM_ALLIANCE = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:45
 CHAT_MSG_RAID_BOSS_EMOTE = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:45
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:31
 categorySort = <table> {
 }
 iconRestore = <table> {
 }
 addon = <table> {
 }
 localization = <table> {
 }
 announces = <table> {
 }
 vb = <table> {
 }
 optionCategories = <table> {
 }
}
cache = <table> {
}
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
x = <table> {
 isPlayer = false
 isAlive = true
 atlas = "Vehicle-SilvershardMines-MineCartRed"
 textureWidth = 64
 isOccupied = false
 y = 0.697970
 x = 0.407835
 name = "Mine Cart"
 textureHeight = 64
 facing = 3.315482
 shouldDrawBelowPlayerBlips = true
}
y = nil
_ = nil
_ = nil
vType = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'x' (a table value)"
GetNumBattlefieldVehicles = <function> defined =[C]:-1
GetBattlefieldVehicleInfo = <function> defined =[C]:-1
identifyCartCoord = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:124
carts = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
pairs = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
identifyCart = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:135
cartTimer = <table> {
 id = "TimerCart"
 text = "%s"
 startedTimers = <table> {
 }
 mod = <table> {
 }
 timer = 9.500000
 option = "TimerCart"
 icon = 136002
}
names = <table> {
 1 = "Top - Down"
 2 = "Top - Up"
 3 = "Middle"
 4 = "Lava - Down"
 5 = "Lava - Up"
}
getDistance = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:104
isValidUpdate = <function> defined @Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua:90
times = <table> {
 1 = 181
 2 = 234
 3 = 129
 4 = 97
 5 = 153
}

**Comment by QartemisT** [comment]
Fixed as of https://github.com/DeadlyBossMods/DBM-PvP/pull/40

Thank you for the report :)
