### ISSUE TITLE
Three errors, happens just by logging in. 

### ISSUE THREAD

**Issue by Marscgm** [DeadlyBossMods/DBM-PvP#50]
WowUp installed. Up to date.  Happens every time I log in, sometimes forces me to dc. Three errors broken by numbers.

1)

> 2324x DPM-Core\DPM-Core-5.1.lua:1393: attempt to call global 'SendAddonMessage' (a nil value)
> [string "@DPM-Core\DPM-Core-5.1.lua"]:1393: in function <DPM-Core\DPM-Core.lua:1384>
> [string "=[C]"]: in function `LoadAddOn'
> [string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
> [string "@FrameXML\UIParent.lua"]:768: in function `Communities_LoadUI'
> [string "@FrameXML\UIParent.lua"]:1055: in function `ToggleCommunitiesFrame'
> [string "@FrameXML\UIParent.lua"]:905: in function `ToggleGuildFrame'
> [string "@FrameXML\MainMenuBarMicroButtons.lua"]:421: in function <FrameXML\MainMenuBarMicroButtons.lua:419>
> [string "=[C]"]: ?
> 
> Locals:
> self = <unnamed> {
>  0 = <userdata>
> }
> event = "ADDON_LOADED"
> (*temporary) = nil
> (*temporary) = "DPMversion"
> (*temporary) = 5.100000
> (*temporary) = "GUILD"
> (*temporary) = "attempt to call global 'SendAddonMessage' (a nil value)"
> 

2)

> 5784x DPM-Core\DPM-Core-5.1.lua:1387: attempt to call global 'SendAddonMessage' (a nil value)
> [string "@DPM-Core\DPM-Core-5.1.lua"]:1387: in function <DPM-Core\DPM-Core.lua:1384>
> 
> Locals:
> self = <unnamed> {
>  0 = <userdata>
> }
> event = "GROUP_ROSTER_UPDATE"
> (*temporary) = nil
> (*temporary) = "DPMversion"
> (*temporary) = 5.100000
> (*temporary) = "RAID"
> (*temporary) = "attempt to call global 'SendAddonMessage' (a nil value)"

3)

> 90x DPM-Core\DPM-Core-5.1.lua:143: attempt to call method 'GetBackdrop' (a nil value)
> [string "@DPM-Core\DPM-Core-5.1.lua"]:143: in function `RuneCreateFrame'
> [string "@DPM-Core\DPM-Core-5.1.lua"]:719: in function `LoadAdjustAuras'
> [string "@DPM-Core\DPM-Core-5.1.lua"]:1400: in function <DPM-Core\DPM-Core.lua:1384>
> 
> Locals:
> name = "DPM_AFrame"
> x = 0
> y = 0
> parent = nil
> width = 210
> height = 325
> move = true
> mouse = true
> rto = nil
> rpoint = nil
> Parent = nil
> FrameLevel = 4
> RelativeTo = "CENTER"
> RelativePoint = "CENTER"
> Fx = 0
> Fy = 0
> FName = "DPM_AFrame"
> FWidth = 210
> FHeight = 325
> MoveAble = true
> MouseAble = true
> FFrame = DPM_AFrame {
>  0 = <userdata>
> }
> (*temporary) = nil
> (*temporary) = DPM_AFrame {
>  0 = <userdata>
> }
> (*temporary) = nil
> (*temporary) = StaticPopup1 {
>  0 = <userdata>
>  SubText = <unnamed> {
>  }
>  ItemFrame = StaticPopup1ItemFrame {
>  }
>  Border = <unnamed> {
>  }
>  button3 = StaticPopup1Button3 {
>  }
>  extraFrame = StaticPopup1ExtraFrame {
>  }
>  button4 = StaticPopup1Button4 {
>  }
>  button2 = StaticPopup1Button2 {
>  }
>  moneyFrame = StaticPopup1MoneyFrame {
>  }
>  button1 = StaticPopup1Button1 {
>  }
>  text = StaticPopup1Text {
>  }
>  editBox = StaticPopup1EditBox {
>  }
>  extraButton = StaticPopup1ExtraButton {
>  }
>  Separator = <unnamed> {
>  }
>  moneyInputFrame = StaticPopup1MoneyInputFrame {
>  }
>  icon = StaticPopup1AlertIcon {
>  }
>  itemFrame = StaticPopup1ItemFrame {
>  }
>  CoverFrame = <unnamed> {
>  }
> }
> (*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
>

**Comment by MysticalOS** [comment]
DPM is a 3rd party module that's grossly out of date and incompatible with DBM. Deadly PVP Mods is not to be mistaken for DBM-PvP or DBM-Core. You will want to remove DPM-Core immediately
