### ISSUE TITLE
Error when pvp

### ISSUE THREAD

**Issue by eeee074** [DeadlyBossMods/DBM-PvP#75]
Date: 2021-01-24 11:52:27
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-StatusBarTimers\DBT.lua line 1561:
   DBT_Bar_13:SetPoint(): trying to anchor to itself
Debug:
   [C]: ?
   [C]: SetPoint()
   DBM-StatusBarTimers\DBT.lua:1561: SetPosition()
   DBM-StatusBarTimers\DBT.lua:539: Append()
   DBM-StatusBarTimers\DBT.lua:813: CreateBar()
   DBM-Core\DBM-Core.lua:10478: Start()
   DBM-PvP\PvPGeneral.lua:313: handler()
   DBM-Core\DBM-Core.lua:854:
      DBM-Core\DBM-Core.lua:841
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v100.0.9
  BagBrother, v
  Bagnon, v9.0.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicTargetHelper, v
  Clique, vv1.0.3-classic
  DBMCore, v1.13.67-14-gbb5f23c
  DBMDefaultSkin, v
  DBMGUI, v
  DBMPvP, vr113
  DBMStatusBarTimers, v
  Decursive, v2.7.8
  DejaClassicStats, v1305r004
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.42
  EMAClassic, vv1.13.5-Release-v0.9(121033)
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  HandyNotes, vv1.6.1
  Hemlock, v1.1.4
  honorspy, v1.7.7
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  NovaInstanceTracker, v1.13
  NovaWorldBuffs, v1.87
  Pawn, v2.4.10
  Questie, v6.2.4
  Scrap, v9.0.1
  ScrapMerchant, v
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.28
  TomTom, vv11306-1.2.0
  VendorPrice, v1.3.8
  WeakAuras, v3.1.8
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=623)

**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
You're using DBM-Core v1.13.67-14, which didn't have all timer fixes synced yet, try v1.13.67-16

**Comment by eeee074** [comment]
thanks for the quick response, just seen updated dbm and updated.  Appears to be ok now.

**Comment by QartemisT** [comment]
We also added some more fixes in r114, so this should be fully solved now :) Closing.
