### ISSUE TITLE
Came back, error when pvping all mods up to date

### ISSUE THREAD

**Issue by eeee074** [DeadlyBossMods/DBM-PvP#76]
Date: 2021-01-25 12:51:22
ID: 1
Error occured in: Global
Count: 1
Message: [string "--[==[ Error in 'ArathiBasinCaptureOrResurr..."] line 15:
   attempt to compare number with nil
Debug:
   [string "--[==[ Error in 'ArathiBasinCaptureOrResurr..."]:15:
      [string "--[==[ Error in 'ArathiBasinCaptureOrResurr..."]:1
   [C]: xpcall()
   WeakAuras\GenericTrigger.lua:543:
      WeakAuras\GenericTrigger.lua:536
   WeakAuras\GenericTrigger.lua:807: ScanWithFakeEvent()
   WeakAuras\GenericTrigger.lua:1091: LoadDisplays()
   WeakAuras\WeakAuras.lua:1662: LoadDisplays()
   WeakAuras\WeakAuras.lua:1486:
      WeakAuras\WeakAuras.lua:1363
   WeakAuras\WeakAuras.lua:1518: ScanForLoads()
   WeakAuras\WeakAuras.lua:1568:
      WeakAuras\WeakAuras.lua:1566
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v100.0.9
  BagBrother, v
  Bagnon, v9.0.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicTargetHelper, v
  Clique, vv1.0.3-classic
  DBMCore, v1.13.67-17-gdba80f2
  DBMDefaultSkin, v
  DBMPvP, vr113
  DBMStatusBarTimers, v
  Decursive, v2.7.8
  DejaClassicStats, v1305r004
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.42
  EMAClassic, vv1.13.5-Release-v0.9(121033)
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  HandyNotes, vv1.6.1
  Hemlock, v1.1.4
  honorspy, v1.7.7
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  NovaInstanceTracker, v1.13
  NovaWorldBuffs, v1.87
  Pawn, v2.4.10
  Questie, v6.2.4
  Scrap, v9.0.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.28
  TomTom, vv11306-1.2.0
  VendorPrice, v1.3.8
  WeakAuras, v3.1.8
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=5d7)

###**Twitch client installed classic/retail version on retail/classic**

**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by QartemisT** [comment]
That's nothing to do with DBM-PvP. Its a WeakAura issue :)
