### ISSUE TITLE
Bug in RBGs with timers

### ISSUE THREAD

**Issue by Malakyte** [DeadlyBossMods/DBM-PvP#80]
Message: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_1:SetPoint.
Time: Thu Feb  4 19:52:37 2021
Count: 2
Stack: Interface\AddOns\DBM-StatusBarTimers\DBT.lua:1513: Action[SetPoint] failed because[Cannot anchor to itself]: attempted from: DBT_Bar_1:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:1513: in function `SetPosition'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:538: in function `Append'
[string "@Interface\AddOns\DBM-StatusBarTimers\DBT.lua"]:809: in function `CreateBar'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:10998: in function `Start'
[string "@Interface\AddOns\DBM-PvP\Battlegrounds\SilvershardMines.lua"]:50: in function `handler'
[string "@Interface\AddOns\DBM-Core\DBM-Core.lua"]:893: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:880>

Locals:

**Comment by amk0** [comment]
Keep getting that too on every single BG. The first one works fine, after that only a /reload inside the subsequent BGs will make it stop appearing until the next one.

**Comment by PreggyPenny** [comment]
Ditto

**Comment by QartemisT** [comment]
Should be resolved as of the latest DBM-Core alpha :)

We will continue to update all DBT related issues over at https://github.com/DeadlyBossMods/DeadlyBossMods/issues/519
