### ISSUE TITLE
Timers are not accurate

### ISSUE THREAD

**Issue by Rippeee** [DeadlyBossMods/DBM-PvP#9]
Timers seems to be off sync, Atleast in Alterac valley  (wow classic)

Once Gy is capped the timer shows -5

So the timer is 5 second short.

**Comment by MysticalOS** [comment]
https://twitter.com/deadlybossmods/status/1207688848446238721

caps take 297 - 308 seconds (random). best dbm can do is show a 297 second timer. the timer COULD be more accurate if blizzard fixed the api that's supposed to return the EXACT time on the map, but otherwise all dbm can do is show the 297 timer, then keep it on screen (with the negative number) to show you that the 297 finished and the cap will finished at any second.

**Comment by Rippeee** [comment]
Don't wana argue, but are u sure its limited by Blizzard api tho? Cuz excample sspvp seems to be accurate everytime. only downside on sspvp is that there is no option to announce it on chat

**Comment by MysticalOS** [comment]
I looked at that mod, it uses 304, which is probably the rough average of the variation, so for all intensive purposes it'll appear more accurate most of time. most of the time the timers will use the average.

But like one in 20 would be at 297 or 308. DBM has always errored on side of caution and used lowest time even if it's rare, so yuo never run into a situation where lets say we actually start a 305 second timer, and then the cap actually happens 7 seconds sooner.

so I guess question is, do you prefer timers to never be early, but sometimes be late? or for them to be as they are now where they are often early, but sometimes late?

as for the limitted by API thing, if the API ACTUALLY worked, we'd always know exact time. it'd never ever be late or early, period. if cap decides it's gonna be 308 or 297, we'd know that from the api. No matter what, the mod is going to sometimes be wrong. Even sspvp is going to be wrong, even if it's only 1 in 20, and it's not the mods fault it's blizzards. Blizzard rarely uses realtime for their timers, they generally use looping scripts or onupdate methods that expire after x cycles, which is what causes the variations.

**Comment by Rippeee** [comment]
So far in BG's  the timer on sspvp have been correct like 100 out of 100 times, so i would prefer to mimic that, atleast in Pvp Mod.  On Pve raiding its better to be early than late.

**Comment by MysticalOS** [comment]
I changed them to 304 for now. You're only one that gave any feedback even though I tweeted it out, which means 100% of feedback wanted them to change.. I'll leave issue open in case more views get added

**Comment by Rippeee** [comment]
sure, thanks mate :)

**Comment by Developaws** [comment]
Closing as timers seem a little more "accurate" now.
