### ISSUE TITLE
DBM Timers/Bars - AV WoW Classic

### ISSUE THREAD

**Issue by VirusViper** [DeadlyBossMods/DBM-PvP#94]
Do I have a bug or something isn't right? I've recently returned to AV in WoW Classic and randomly the timer bars for graveyards and bunkers all just reset to the 5 minute mark and then nothing is correct... Can someone advise if I need to delete something or these are problems with the addon?

Thanks.

**Comment by lonniejk** [comment]
same here, have no idea what the issue is. it's mad frustrating. i've reset settings, deleted the addon, reinstalled it, etc. nothing

**Comment by QartemisT** [comment]
I have a potential fix that's going out now. If this issue persists, please tag me in this issue and I'll re-open it and check further :)

**Comment by VirusViper** [comment]
@QartemisT Still happening, just in AV, died and all timers went to 5mins. Go the update from Curse earlier version r119

**Comment by MysticalOS** [comment]
it should actually be fixed now, in latest alpha. Try it out. @QartemisT don't tag an unconfirmed fix before it's been tested. TBC stuff wasn't even done yet and it was tagged as a stable tbc release. :P

**Comment by VirusViper** [comment]
> 
> 
> it should actually be fixed now, in latest alpha. Try it out. @QartemisT don't tag an unconfirmed fix before it's been tested. TBC stuff wasn't even done yet and it was tagged as a stable tbc release. :P

Thanks, I'm going to sound like a total noob now, how do I get the alpha as normally i grab them all from the classic release on curse. Is the zip file here for all versions of WoW?

**Comment by VirusViper** [comment]
@MysticalOS - Da man! It works perfect like it used to 👍
