### ISSUE TITLE
PVP Bars reset or disappear after each death in Alterac Valley

### ISSUE THREAD

**Issue by eeee074** [DeadlyBossMods/DBM-PvP#95]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No I have ELVui Enabled

**Which version of DeadlyBossMods are you using?**
1.13.71 DBM

**Was it working in a previous version? If yes, which was the last good one?**
hasn't worked properly in a bit

**Additional context**

**Comment by QartemisT** [comment]
Merging into #94
