### ISSUE TITLE
Broken timer bar

### ISSUE THREAD

**Issue by Molkree** [DeadlyBossMods/DBM-PvP#99]
**Describe the bug**
Flickering of the small bar timer and then big bar timer appeared in place of small bar timer (left corner of the screen, should be in the middle).

**Do you have an error log of what happened?**
No Lua errors.

**To Reproduce**
I don't have a reliable way to reproduce it, I hit it the first time on May 7 and seen it twice in this BG (separate matches).

**Screenshots**

![image](https://user-images.githubusercontent.com/12860284/117500710-ab09f600-af85-11eb-9391-0f056ddf5449.png)

Next frame (from video, video is 30fps):
![image](https://user-images.githubusercontent.com/12860284/117500765-bfe68980-af85-11eb-9d56-a0fe313c731b.png)

Next frame:
![image](https://user-images.githubusercontent.com/12860284/117500799-ca088800-af85-11eb-89a3-fa5a639cb7aa.png)

27 seconds into the video bar starts to enlarge:
![image](https://user-images.githubusercontent.com/12860284/117501179-5fa41780-af86-11eb-89a8-8020fbbd883c.png)

First it moves upward:
![image](https://user-images.githubusercontent.com/12860284/117501233-70ed2400-af86-11eb-863b-f997e5430eb7.png)

It should have transitioned to the middle of the screen though.

Then it becomes bigger:
![image](https://user-images.githubusercontent.com/12860284/117501297-84988a80-af86-11eb-8bd4-7656bd70ac10.png)

Next frame:
![image](https://user-images.githubusercontent.com/12860284/117501508-cd504380-af86-11eb-8608-6a30ce031050.png)

Still flickering in this state:
![image](https://user-images.githubusercontent.com/12860284/117501609-f244b680-af86-11eb-98fc-31cd93b91470.png)
![image](https://user-images.githubusercontent.com/12860284/117501631-fa9cf180-af86-11eb-8f4b-990a9dc01005.png)

And it even looks like bars are overlaid on top of each other? Or maybe just the "shiny" vertical line is in the correct position. Or maybe just video artifact xD
![image](https://user-images.githubusercontent.com/12860284/117501733-228c5500-af87-11eb-886a-195636d63395.png)

Also noticed that when big bar timer "Horde wins" expired Horde actually captured waterworks at this exact time, that might be what was tracked.

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of DeadlyBossMods are you using?**
DBM at this [commit](https://github.com/DeadlyBossMods/DeadlyBossMods/commit/046e27bea44dab2d08becb9c6eaab45717285c89), DBM-PvP at [r122](https://github.com/DeadlyBossMods/DBM-PvP/releases/tag/r122).

**Was it working in a previous version? If yes, which was the last good one?**
Haven't seen this behavior before but I haven't run any BGs for a week or more.

**Additional context**
[Video](https://drive.google.com/file/d/1VA9XEaFRda6r6IZaRNOj6S6mEWxOs9It/view) on Google Drive, it's 120MB download (1min 36sec). Oh, there's embedded player on GDrive, cool.

**Comment by Molkree** [comment]
I've just seen a similar issue with timers, now in Arathi Basin.
Sometimes some timers were flickering like above so I'm pretty sure they were overlaid on top of each other at some point.

Weird placements like this:
![image](https://user-images.githubusercontent.com/12860284/121428077-1593c480-c97e-11eb-918f-e2619ac19462.png)

Most of the bg some timers were missing, like here no Ally timer:
![image](https://user-images.githubusercontent.com/12860284/121428189-32c89300-c97e-11eb-85a2-a8f8e4db45eb.png)

Sometimes there were no timers at all, meaning time to win timer couldn't be hidden behind others so idk.
It appeared at the very end with 2sec time which wasn't ticking and just disappeared after that 🤷‍♂️

**Comment by MysticalOS** [comment]
I still often wonder if it's even worth supporting pvp mods. no pvp mods, no bugs. Considering hours wasted already trying to fix what is seemingly a lost cause, I wonder if it's even worth it anymore. I can always direct users back to Capping.

**Comment by QartemisT** [comment]
Weird timer positioning should be resolved :)
